name: kick26
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  gap: ^3.0.1
  intl: ^0.20.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # adaptive_icon_foreground: "assets/icon/foreground.png" # Path to your foreground image for adaptive icons
  adaptive_icon_background: "#141414"

  web:
    generate: true
    image_path: "assets/icons/icon_launcher.png"
    background_color: "#hexcode"
    theme_color: "#141414"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: PoppinsThin
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          style: normal
    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          style: normal
    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          style: normal
    - family: PoppinsSemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          style: normal
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          style: normal
    - family: PoppinsExtraBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          style: normal
    - family: PoppinsLight
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          style: normal
    - family: PoppinsExtraLight
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          style: normal
